spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/devcompass_test}
    username: ${DB_USERNAME:devcompass}
    password: ${DB_PASSWORD:devcompass}
    driver-class-name: org.postgresql.Driver
